SOM/SOM/Controllers/ABMController.cs
using SOM.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SOM.Application;
using System.Web.Script.Serialization;
using System.Threading.Tasks;
using System.IO;
using ClosedXML.Excel;
namespace SOM.Controllers
{
    public class ABMController : Controller
    {
        //
        // GET: /ABM/
        ModuloCursosManagementService moduloCursosManagementService = new ModuloCursosManagementService();
        CursosManagementService cursosManagementService = new CursosManagementService();
        LeccionManagementService leccionManagementService = new LeccionManagementService();
        AgenciaManagementService agenciaManagementService = new AgenciaManagementService();
        RolManagementService rolManagementService = new RolManagementService();
        UsuarioManagementService usuarioManagementService = new UsuarioManagementService();
        public ActionResult Modulo()
        {
            return View( new indexViewModel());
        }
        public ActionResult Usuario()
        {
            return View(new indexViewModel());
        }
        public ActionResult Curso(int id_modulo, int? id_curso)
        {
            var miViewModel = new ABMViewModelController().getABMViewModel(id_modulo, id_curso);
            return View(miViewModel);
        }
        public ActionResult Leccion(int id_modulo, int id_curso)
        {
            var miViewModel = new ABMViewModelController().getLessonABMViewModel(id_modulo, id_curso);
            return View(miViewModel);
        }
        public ActionResult Pregunta(int id_modulo, int id_curso, int id_leccion)
        {
            var miViewModel = new ABMViewModelController().getQuestionABMViewModel(id_modulo, id_curso, id_leccion);
            return View(miViewModel);
        }
        public ActionResult Certificacion(int id_modulo, int id_curso, int id_leccion)
        {
            var miViewModel = new ABMViewModelController().getQuestionABMViewModel(id_modulo, id_curso, id_leccion);
            return View(miViewModel);
        }
        public ActionResult Respuesta(int id_modulo, int id_curso, int id_leccion, int id_pregunta)
        {
            var miViewModel = new ABMViewModelController().getAnswerABMViewModel(id_modulo, id_curso, id_leccion, id_pregunta);
            return View(miViewModel);
        }
        public ActionResult Agencia()
        {
            return View(new indexViewModel());
        }
        public ActionResult Rol()
        {
            return View(new indexViewModel());
        }
        public ActionResult RolModulo(int id_rol)
        {
            RolModuleViewModel miViewModel = new ABMViewModelController().getRolModuleViewModel(id_rol);
            return View(miViewModel);
        }
        public ActionResult RolCurso(int id_rol, int id_modulo, int? id_curso)
        {
            var miViewModel = new ABMViewModelController().getRolCourseViewModel(id_rol, id_modulo, id_curso);
            return View(miViewModel);
        }
        public ActionResult destacado()
        {
            return View(new indexViewModel());
        }
        public ActionResult subirArchivos()
        {
            return View(new indexViewModel());
        }
        #region Modulos
            public ActionResult GetModulos()
            {
                //ModuloCursosManagementService moduloCursosManagementService = new ModuloCursosManagementService();
                var misModulos = moduloCursosManagementService.getModulos();

                return Json(new { modulos = misModulos }, JsonRequestBehavior.AllowGet);

            }
            public ActionResult AgregarModulo(string Nombre, string Controlador, string View, string Style){
                
                string Tags = "";
                string Mensaje = moduloCursosManagementService.agregarModulo(Nombre, Controlador, View, Style, Tags);
                return Json(new { Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);
            }
            public ActionResult ModificarModulo(int ID_Modulo, string Nombre, string Controlador, string View, string Style)
            {
                string Tags = "";
                string Mensaje = moduloCursosManagementService.modificarModulo(ID_Modulo, Nombre, Controlador, View, Style, Tags);
                return Json(new { Mensaje = Mensaje  }, JsonRequestBehavior.AllowGet);
            }
            public ActionResult InhabilitarModulo(int ID_Modulo)
            {
                string Mensaje = moduloCursosManagementService.inhabilitarModulo(ID_Modulo);
                return Json(new { Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);
            }
            public ActionResult HabilitarModulo(int ID_Modulo)
            {
                string Mensaje = moduloCursosManagementService.habilitarModulo(ID_Modulo);
                return Json(new { Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);
            }
        #endregion
        #region Cursos
            public ActionResult GetCursos(int id_modulo, int? id_curso)
            {
                //ModuloCursosManagementService moduloCursosManagementService = new ModuloCursosManagementService();
                var misCursos = cursosManagementService.getCursos(id_modulo, id_curso);

                return Json(new { cursos = misCursos }, JsonRequestBehavior.AllowGet);

            }
            public ActionResult AgregarCurso(int Id_modulo, string Nombre, string Descripcion, string Controlador, string View, string Style,string Imagen, int? Parent)
            {

                string Mensaje = cursosManagementService.agregarCurso(Id_modulo, Nombre, Descripcion, Controlador, View, Style, Imagen, Parent);
                return Json(new { Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);
            }
            public ActionResult ModificarCurso(int ID_Modulo, int Id_curso, string Nombre, string Descripcion, string Controlador, string View, string Style, string Imagen)
            {

                string Mensaje = cursosManagementService.modificarCurso(ID_Modulo, Id_curso, Nombre, Descripcion, Controlador, View, Style, Imagen);
                return Json(new { Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);
            }
            public ActionResult InhabilitarCurso(int ID_Modulo, int Id_curso)
            {
                string Mensaje = cursosManagementService.InhabilitarCurso(ID_Modulo, Id_curso);
                return Json(new { Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);
            }
            public ActionResult HabilitarCurso(int ID_Modulo, int Id_curso)
            {
                string Mensaje = cursosManagementService.HabilitarCurso(ID_Modulo, Id_curso);
                return Json(new { Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);
            }
            
        #endregion
        #region Lecciones
            public ActionResult GetLeccion(int id_modulo, int id_curso)
            {
                //ModuloCursosManagementService moduloCursosManagementService = new ModuloCursosManagementService();
                var misLecciones = leccionManagementService.getLecciones(id_modulo, id_curso);

                return Json(new { lecciones = misLecciones }, JsonRequestBehavior.AllowGet);

            }
            public ActionResult AgregarLeccion(int Id_modulo, int Id_curso, string Nombre, string Descripcion, string Imagen, string Video, decimal Pje_aprobacion)
            {
                string Mensaje = leccionManagementService.AgregarLeccion(Id_modulo, Id_curso, Nombre,  Descripcion,  Imagen,  Video,  Pje_aprobacion);
                return Json(new { Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);
            }
            public ActionResult ModificarLeccion(int Id_modulo, int Id_curso, int Id_leccion, string Nombre, string Descripcion, string Imagen, string Video, decimal Pje_aprobacion, int? Orden)
            {
                string Mensaje = leccionManagementService.ModificarLeccion(Id_modulo, Id_curso, Id_leccion, Nombre, Descripcion, Imagen, Video, Pje_aprobacion, Orden);
                return Json(new { Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);
            }
            public ActionResult InhabilitarLeccion(int ID_Modulo, int Id_curso, int Id_leccion)
            {
                string Mensaje = leccionManagementService.InhabilitarLeccion(ID_Modulo, Id_curso, Id_leccion);
                return Json(new { Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);
            }
            public ActionResult HabilitarLeccion(int ID_Modulo, int Id_curso, int Id_leccion)
            {
                string Mensaje = leccionManagementService.HabilitarLeccion(ID_Modulo, Id_curso, Id_leccion);
                return Json(new { Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);
            }

        #endregion 
        #region Pregunta

            public ActionResult GetPregunta(int id_modulo, int id_curso, int Id_leccion)
            {

                var misPreguntas = leccionManagementService.GetPregunta(id_modulo, id_curso, Id_leccion);
                return Json(new { preguntas = misPreguntas }, JsonRequestBehavior.AllowGet);

            }
            public ActionResult AgregarPregunta(int Id_modulo, int Id_curso, int Id_leccion, string Nombre, string Correcto, string Incorrecto)
            {
                string Mensaje = leccionManagementService.AgregarPregunta(Id_modulo, Id_curso, Id_leccion, Nombre, Correcto, Incorrecto);
                return Json(new { Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);
            }
            public ActionResult ModificarPregunta(int Id_modulo, int Id_curso, int Id_leccion, int Id_pregunta, string Nombre, string Correcto, string Incorrecto, decimal Cant_puntos)
            {
                string Mensaje = leccionManagementService.ModificarPregunta(Id_modulo, Id_curso, Id_leccion, Id_pregunta, Nombre, Correcto, Incorrecto, Cant_puntos);

SOM/SOM/Views/ABM/agencia.cshtml
@model SOM.ViewModels.indexViewModel
@using SOM.Entities
@using SOM.HelperExtensionNameSpace

@{
    ViewBag.Title = "Sidepro SOM - Agencias";
    Layout = "~/Views/Shared/_LayoutABM.cshtml";
}
<script>
    var urlAgencias = '@Url.Action("GetAgencias", "ABM")';
    var urlAgregarAgencia = '@Url.Action("AgregarAgencia","ABM")';
    var urlUpdateAgencia = '@Url.Action("ModificarAgencia","ABM")';
    var urlTipoAgencias = '@Url.Action("GetTipoAgencias", "ABM")';
    $(document).ready(function () {
        start();
    })
    function start() {

        $.ajax({
            type: "GET",
            dataType: "json",
            url: urlAgencias,
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                var agencias = data.Agencias;
                llenarGrilla(agencias);
            },
            error: function (xhr, status, error) {
                alert(error);
            }
        });

        function llenarGrilla(agencias) {
            var tbody = $('#tbody');
            var trs = '';


            for (var i = 0; i < agencias.length; i++) {

                trs = trs + '<tr>';
                //                trs = trs + '    <td>' + modulos[i]. + '</td>';
                trs = trs + '    <td>' + agencias[i].Nombre + '</td>';
                trs = trs + '    <td>' + agencias[i].Documento + '</td>';
                trs = trs + '    <td>' + agencias[i].Email + '</td>';
                trs = trs + '    <td>' + agencias[i].TipoAgencia + '</td>';
                trs = trs + '    <td><i class="glyphicon glyphicon-edit" onClick="updateAgency(' + agencias[i].ID_Agencia + ', \'' + agencias[i].Nombre + '\', \'' + agencias[i].Documento + '\', \'' + agencias[i].Email + '\', ' + agencias[i].Cod_tipo_agencia + ')"   onmouseover="" style="cursor: pointer;"></i></td>';
                trs = trs + '</tr>';
            }
            tbody.html(trs);
        }

    }
    function updateAgency(id_agencia, Agencia, Documento, Email, cod_tipo_agencia) {
        $("#updateModal").modal("show");
        $('#updateModalTitle').html(Agencia);
        var tbody = '';

        tbody = tbody + '<tr><td><label>Punto de Venta</label></td><td style="padding-bottom:8px; padding-left:8px;"><input type="text" id="txtAgencia" style="-moz-border-radius: 5px; -webkit-border-radius: 5px; border-radius: 10px; padding: 0 4px 0 4px;width:100%" value="'+ Agencia +'"  /></td></tr>';
        tbody = tbody + '<tr><td><label>Documento</label></td><td style="padding-bottom:8px; padding-left:8px"><input type="text" id="txtDocumento" style="-moz-border-radius: 5px; -webkit-border-radius: 5px; border-radius: 10px; padding: 0 4px 0 4px;width:100%" value="'+ Documento +'" /></td></tr>';
        tbody = tbody + '<tr><td><label>Email</label></td><td style="padding-bottom:8px; padding-left:8px"><input type="text" id="txtEmail" style="-moz-border-radius: 5px; -webkit-border-radius: 5px; border-radius: 10px; padding: 0 4px 0 4px;width:100%" value="'+Email+'" /></td></tr>';
        tbody = tbody + '<tr><td><label>Tipo Agencia</label></td><td style="padding-bottom:8px; padding-left:8px">';
        tbody = tbody + '        <select id="ddlTipoAgente" style="-moz-border-radius: 5px; -webkit-border-radius: 5px; border-radius: 10px; padding: 0 4px 0 4px;width:100%"></select></td>';
        tbody = tbody + '</tr>';
        $('#updateTbody').html(tbody);
        cargarTipoAgecia( $('#ddlTipoAgente'), cod_tipo_agencia);

        var footer = '';
        footer = footer + '<input type="button" class="btn btn-success" onClick="modificarAgencia(' + id_agencia + ')" value="Aceptar">'; 
        footer = footer + '<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar">';

        $('#updateModalFooter').html(footer);


        $('#divNombre').html(Agencia);
    }
    function addAgencia() {

        $("#addModal").modal("show");
        cargarTipoAgecia( $('#ddlTipoAgenteA') ,- 10);
    }
    function addAgency() {

        var txt_agencia, nro_doc, txt_email, cod_tipo_agencia;
        txt_agencia =  $('#txtAgenciaA').val();
        nro_doc =  $('#txtDocumentoA').val();
        txt_email = $('#txtEmailA').val();
        cod_tipo_agencia = $('#ddlTipoAgenteA').val();

        var mailValido = validateEmail(txt_email);
        if (mailValido){
            $.ajax({
                type: "GET",
                dataType: "json",
                url: urlAgregarAgencia,
                contentType: "application/json; charset=utf-8",
                data: { Agencia: txt_agencia, Documento: nro_doc, Email: txt_email, TipoAgencia: cod_tipo_agencia },
                success: function (data) {
                    $("#addModal").modal("hide");

                    if (data.Mensaje == '') {
                        alert('El punto de venta ha sido agregado con éxito!.');
                    } else {
                        alert(data.Mensaje);
                    }
                    start();
                },
                error: function (xhr, status, error) {
                    alert('Ocurrió un error al actualizar el registro, por favor comuniquese con el administrador.');
                }
            });
        } else {
            alert('Error, el email ingresado es inválido.');
        }
    }
    function modificarAgencia(id_agencia) {


        var txt_agencia, nro_doc, txt_email, cod_tipo_agencia;
        txt_agencia = $('#txtAgencia').val();
        nro_doc = $('#txtDocumento').val();
        txt_email = $('#txtEmail').val();
        cod_tipo_agencia = $('#ddlTipoAgente').val();

        var mailValido = validateEmail(txt_email);
        if (mailValido){        
            $.ajax({
                type: "GET",
                dataType: "json",
                url: urlUpdateAgencia,
                contentType: "application/json; charset=utf-8",
                data: { id_agencia: id_agencia, Agencia: txt_agencia, Documento: nro_doc, Email: txt_email, TipoAgencia: cod_tipo_agencia  },
                success: function (data) {

                    if (data.Mensaje == '') {
                        alert('El punto de venta ha sido modificado con éxito!.');
                    } else {
                        alert(data.Mensaje);
                    }
                    start();
                    $('#updateTbody').html('');
                    $('#updateModalFooter').html('');
                    $("#updateModal").modal("hide");
                },
                error: function (xhr, status, error) {
                    alert('Ocurrió un error al actualizar el registro, por favor comuniquese con el administrador.');
                }
            });
        } else {
            alert('Error, el email ingresado es inválido.');
        }
    }
    function cargarTipoAgecia(control, cod_tipo_agencia) {

        $.ajax({
            type: "GET",
            dataType: "json",
            url: urlTipoAgencias,
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                var tipoAgencias = data.TipoAgencias;
                completarSelect(control,tipoAgencias, cod_tipo_agencia);
            },
            error: function (xhr, status, error) {
                alert(error);
            }
        });
    }
    function completarSelect(control, tipoAgencias, cod_tipo_agencia) {
        var miSelect = control;// $('#ddlTipoAgente');

        var misDatos = '';
        for (var i = 0; i < tipoAgencias.length; i++) {
            if (tipoAgencias[i].Cod_tipo_agencia == cod_tipo_agencia){
                misDatos = misDatos + '<option value="' + tipoAgencias[i].Cod_tipo_agencia + '" selected >' + tipoAgencias[i].Nombre + '</option>'
            } else {
                misDatos = misDatos + '<option value="' + tipoAgencias[i].Cod_tipo_agencia + '">' + tipoAgencias[i].Nombre + '</option>'
            }
        }

        miSelect.html(misDatos);
    }
    function validateEmail(email) {
        var re = /^([\w-]+(?:\.[\w-]+)*)@@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
        return re.test(email);
    }


</script>


<div class="site-content site-content--default">
    <div class="card">
        <div class="card__header">
            <h2><a href="javascript:void(0)">Puntos de Venta</a></h2>
        </div>

        <div class="card__content">
            <div class="table__container" style="overflow:auto;max-height:450px;">
                <table class=" table table--default">
                <thead>
                    <tr>
                        <th>Punto de Venta</th>
                        <th>Documento</th>
                        <th>Email</th>
                        <th>Tipo de Puntos de Venta</th>
                        <th style="width: 2px; padding:0;"></th>
                    </tr>
                </thead>
                <tbody id="tbody"></tbody>
                </table>

            </div>
            <div style="padding-top:10px">
                <input type="button" class="btn btn-success" onclick="addAgencia()" value="Agregar" style="float: right;">
            </div>
        </div>
    </div>

</div>
<div id="updateModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" id="updateModalTitle"></h4>
            </div>
            <div class="modal-body">
                <table>
                    <thead><tr><th style="width:30%"></th><th style="width:70%"></th></tr></thead>
                    <tbody id="updateTbody"></tbody>
                </table>
            </div>
            <div class="modal-footer" id="updateModalFooter">
                <input type="button" class="btn btn-success" data-dismiss="modal" value="Aceptar">
                <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar">
            </div>
        </div>

    </div>
</div>

<div id="addModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" id="updateModalTitle">Agregar Punto de Venta</h4>
            </div>
            <div class="modal-body">
                <table>
                    <thead><tr><th style="width:30%"></th><th style="width:70%;"></th></tr></thead>
                    <tbody id="addTbody">
                        <tr><td><label>Agencia</label></td><td style="padding-bottom:8px; padding-left:8px;"><input type="text" id="txtAgenciaA" value="" style="-moz-border-radius: 5px; -webkit-border-radius: 5px; border-radius: 10px; padding: 0 4px 0 4px;width:100%" /></td></tr>
                        <tr><td><label>Documento</label></td><td style="padding-bottom:8px; padding-left:8px"><input type="text" id="txtDocumentoA" style="-moz-border-radius: 5px; -webkit-border-radius: 5px; border-radius: 10px; padding: 0 4px 0 4px;width:100%" value="" /></td></tr>
                        <tr><td><label>Email</label></td><td style="padding-bottom:8px; padding-left:8px"><input type="text" id="txtEmailA" style="-moz-border-radius: 5px; -webkit-border-radius: 5px; border-radius: 10px; padding: 0 4px 0 4px;width:100%" value="" /></td></tr>
                        <tr><td><label>Tipo Agencia</label></td><td style="padding-bottom:8px; padding-left:8px">
                                <select id="ddlTipoAgenteA" style="-moz-border-radius: 5px; -webkit-border-radius: 5px; border-radius: 10px; padding: 0 4px 0 4px;width:100%">
                                    <option value="hola">Hola</option>
                                </select>
                            </td>
                        </tr>
                    </tbody>
                </table>

            </div>
            <div class="modal-footer" id="updateModalFooter">
                <input type="button" class="btn btn-success" onclick="addAgency()" value="Aceptar">
                <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar" > @*data-dismiss="modal"*@
            </div>
        </div>

    </div>
</div>

SOM/SOM/Views/ABM/rol.cshtml
@model SOM.ViewModels.indexViewModel
@using SOM.Entities
@using SOM.HelperExtensionNameSpace

@{
    ViewBag.Title = "Sidepro SOM - Roles";
    Layout = "~/Views/Shared/_LayoutABM.cshtml";
}
<script>
    var urlRoles = '@Url.Action("GetRoles", "ABM")';
    var urlAgregarRol = '@Url.Action("AgregarRol","ABM")';
    var urlUpdateRol = '@Url.Action("ModificarRol","ABM")';

    $(document).ready(function () {
        start();
    })
    function start() {

        $.ajax({
            type: "GET",
            dataType: "json",
            url: urlRoles,
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                var roles = data.Roles;
                llenarGrilla(roles);
            },
            error: function (xhr, status, error) {
                alert(error);
            }
        });

        function llenarGrilla(roles) {
            var tbody = $('#tbody');
            var trs = '';


            for (var i = 0; i < roles.length; i++) {

                trs = trs + '<tr>';
                trs = trs + '    <td>' + roles[i].Nombre + '</td>';
                trs = trs + '    <td><i class="glyphicon glyphicon-edit" onClick="updateRole(' + roles[i].ID_Rol + ', \'' + roles[i].Nombre + '\')"   onmouseover="" style="cursor: pointer;"></i></td>';
                trs = trs + '    <td><i class="glyphicon glyphicon-share-alt"  onClick="goToRoleModule(' + roles[i].ID_Rol + ')"  onmouseover="" style="cursor: pointer;"></i></td>';
                trs = trs + '</tr>';
            }
            tbody.html(trs);
        }

    }
    function updateRole(id_rol, Nombre) {
        $("#updateModal").modal("show");
        $('#updateModalTitle').html(Nombre);
        var tbody = '';

        tbody = tbody + '<tr><td><label>Rol</label></td><td style="padding-bottom:8px; padding-left:8px;"><input type="text" id="txtRol" style="-moz-border-radius: 5px; -webkit-border-radius: 5px; border-radius: 10px; padding: 0 4px 0 4px;width:100%" value="'+ Nombre +'"  /></td></tr>';
        $('#updateTbody').html(tbody);
        
        var footer = '';
        footer = footer + '<input type="button" class="btn btn-success" onClick="modificarRol(' + id_rol + ')" value="Aceptar">';
        footer = footer + '<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar">';

        $('#updateModalFooter').html(footer);


        $('#divNombre').html(Nombre);
    }
    function addRol() {

        $("#addModal").modal("show");
    }
    function addRole() {

        var txt_rol;
        txt_rol =  $('#txtRolA').val();
        $.ajax({
            type: "GET",
            dataType: "json",
            url: urlAgregarRol,
            contentType: "application/json; charset=utf-8",
            data: { Rol: txt_rol },
            success: function (data) {
                $("#addModal").modal("hide");
                if (data.Mensaje == '') {
                    alert('El rol ha sido agregado con éxito!.');
                } else {
                    alert(data.Mensaje);
                }
                start();
            },
            error: function (xhr, status, error) {
                alert('Ocurrió un error al actualizar el registro, por favor comuniquese con el administrador.');
            }
        });
    }

    function modificarRol(id_rol) {
        var txt_rol;
        txt_rol = $('#txtRol').val();

        $.ajax({
            type: "GET",
            dataType: "json",
            url: urlUpdateRol,
            contentType: "application/json; charset=utf-8",
            data: { ID_Rol: id_rol, Rol: txt_rol  },
            success: function (data) {

                if (data.Mensaje == '') {
                    alert('El rol ha sido modificado con éxito!.');
                } else {
                    alert(data.Mensaje);
                }
                start();
                $('#updateTbody').html('');
                $('#updateModalFooter').html('');
                $("#updateModal").modal("hide");
            },
            error: function (xhr, status, error) {
                alert('Ocurrió un error al actualizar el registro, por favor comuniquese con el administrador.');
            }
        });
    }
    function goToRoleModule(id_rol) {
        window.location.assign(window.location.origin + "/SOM/ABM/rolModulo?id_rol=" + id_rol); //SideproMovistar
    }
</script>


<div class="site-content site-content--default">
    <div class="card">
        <div class="card__header">
            <h2><a href="javascript:void(0)">Roles</a></h2>
        </div>

        <div class="card__content">
            <div class="table__container" >
                <table class=" table table--default">
                    <thead>
                        <tr>
                            <th>Rol</th>
                            <th style="width: 2px; padding:0;"></th>
                            <th style="width: 2px; padding:0;"></th>
                        </tr>
                    </thead>
                    <tbody id="tbody"></tbody>
                </table>

            </div>
            <div style="padding-top:10px">
                <input type="button" class="btn btn-success" onclick="addRol()" value="Agregar" style="float: right;">
            </div>
        </div>
    </div>

</div>
<div id="updateModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" id="updateModalTitle"></h4>
            </div>
            <div class="modal-body">
                <table>
                    <thead><tr><th style="width:30%"></th><th style="width:70%"></th></tr></thead>
                    <tbody id="updateTbody"></tbody>
                </table>
            </div>
            <div class="modal-footer" id="updateModalFooter">
                <input type="button" class="btn btn-success" data-dismiss="modal" value="Aceptar">
                <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar">
            </div>
        </div>

    </div>
</div>

<div id="addModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" id="updateModalTitle">Agregar Rol</h4>
            </div>
            <div class="modal-body">
                <table>
                    <thead><tr><th style="width:30%"></th><th style="width:70%;"></th></tr></thead>
                    <tbody id="addTbody">
                        <tr><td><label>Rol</label></td><td style="padding-bottom:8px; padding-left:8px;"><input type="text" id="txtRolA" value="" style="-moz-border-radius: 5px; -webkit-border-radius: 5px; border-radius: 10px; padding: 0 4px 0 4px;width:100%" /></td></tr>
                    </tbody>
                </table>

            </div>
            <div class="modal-footer" id="updateModalFooter">
                <input type="button" class="btn btn-success" onclick="addRole()" value="Aceptar">
                <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar"> @*data-dismiss="modal"*@
            </div>
        </div>

    </div>
</div>